#!/bin/bash 
refresh_data_base(){
	sudo pamac update --force-refresh
}

start_timer(){
	start=`date +%s.%N`
}

list_package(){
	read_package=$(cat package_listed)
	list_package=( $read_package )
}

count_package(){
	number_of_files=${#list_package[@]}
}

install_package(){
	for (( i=0; i<$number_of_files; i++ )); do 
		sudo pacman -S "${list_package[$i]}" 
	done
}

end_timer(){
	end=`date +%s.%N`
}

get_info(){
	runtime=$(echo "$end - $start" | bc -l )
	echo $(date +%D) : this script took $runtime seconds to install these $number_of_files packages. >> install_softwares_log; sleep 5 #; reboot
}

main(){
	refresh_data_base
	start_timer
	list_package
	count_package
	install_package
	end_timer
	get_info
}
main
